import type {
  Order,
  Category,
  ShippingMethodConfig,
  PaymentMethodConfig,
  StoreConfig,
  Extra,
} from "./types"

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Hamburguesas", order: 1, active: true },
  { id: "cat-2", name: "Papas", order: 2, active: true },
  { id: "cat-3", name: "Bebidas", order: 3, active: true },
  { id: "cat-4", name: "Combos", order: 4, active: true },
  { id: "cat-5", name: "Postres", order: 5, active: false },
]

export const mockExtras: Extra[] = [
  { id: "extra-1", name: "Medallon extra", price: 1200, inStock: true },
  { id: "extra-2", name: "Bacon", price: 800, inStock: true },
  { id: "extra-3", name: "Huevo frito", price: 500, inStock: true },
  { id: "extra-4", name: "Cheddar extra", price: 400, inStock: true },
  { id: "extra-5", name: "Cebolla crispy", price: 350, inStock: false },
  { id: "extra-6", name: "Jalapenos extra", price: 300, inStock: true },
  { id: "extra-7", name: "Palta extra", price: 600, inStock: true },
  { id: "extra-8", name: "Salsa cheddar", price: 350, inStock: true },
  { id: "extra-9", name: "Bacon extra", price: 600, inStock: true },
  { id: "extra-10", name: "Ketchup extra", price: 0, inStock: true },
  { id: "extra-11", name: "Upgrade papas cheddar", price: 900, inStock: true },
]

export const mockShippingMethods: ShippingMethodConfig[] = [
  {
    id: "ship-1",
    name: "Retiro en local",
    description: "El cliente retira en el local",
    cost: 0,
    active: true,
  },
  {
    id: "ship-2",
    name: "Delivery",
    description: "Envio a domicilio",
    cost: 800,
    active: true,
  },
]

export const mockPaymentMethods: PaymentMethodConfig[] = [
  {
    id: "pay-1",
    name: "Efectivo",
    description: "Pago al recibir",
    adjustment: 0,
    active: true,
  },
  {
    id: "pay-2",
    name: "Transferencia",
    description: "10% de descuento",
    adjustment: -10,
    active: true,
  },
  {
    id: "pay-3",
    name: "MercadoPago",
    description: "10% de recargo",
    adjustment: 10,
    active: true,
  },
]

export const mockStoreConfig: StoreConfig = {
  name: "CABUS HAMBURGUESAS",
  logo: "/images/hero-burger.jpg",
  coverImage: "/images/hero-burger.jpg",
  description: "Las mejores smash burgers de la ciudad. Ingredientes frescos, sabor inigualable.",
  tagline: "Smash Burgers de Verdad",
  whatsapp: "5493511234567",
  isOpen: true,
  estimatedCloseTime: "23:00",
  messageTemplates: {
    orderConfirmation: "Hola {{nombre}}! Tu pedido #{{pedido_id}} fue confirmado. Estamos preparandolo.",
    orderReady: "{{nombre}}, tu pedido #{{pedido_id}} esta listo! {{metodo_envio}}",
    orderDelivery: "{{nombre}}, tu pedido #{{pedido_id}} esta en camino! Llega en aprox. 30 min.",
  },
}

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    items: [
      {
        id: "ci-1",
        product: {
          id: "burger-1",
          name: "Clasica CABUS",
          description: "",
          price: 4500,
          image: "/images/burger-clasica.jpg",
          category: "Hamburguesas",
          inStock: true,
          extras: [],
        },
        quantity: 2,
        selectedExtras: [{ id: "extra-2", name: "Bacon", price: 800, inStock: true }],
        observations: "",
        totalPrice: 10600,
      },
      {
        id: "ci-2",
        product: {
          id: "papas-1",
          name: "Papas Cheddar & Bacon",
          description: "",
          price: 3200,
          image: "/images/papas-cheddar.jpg",
          category: "Papas",
          inStock: true,
          extras: [],
        },
        quantity: 1,
        selectedExtras: [],
        observations: "",
        totalPrice: 3200,
      },
    ],
    subtotal: 13800,
    shippingCost: 800,
    paymentAdjustment: 0,
    total: 14600,
    customer: {
      name: "Juan Perez",
      phone: "3511234567",
      email: "juan@mail.com",
      shippingMethod: "delivery",
      street: "San Martin",
      number: "450",
      neighborhood: "Centro",
      paymentMethod: "efectivo",
      cashAmount: "15000",
      observations: "",
    },
    status: "PENDIENTE",
    createdAt: "2026-02-21T14:32:00",
  },
  {
    id: "ORD-002",
    items: [
      {
        id: "ci-3",
        product: {
          id: "combo-1",
          name: "Combo Clasico",
          description: "",
          price: 7200,
          image: "/images/combo-clasico.jpg",
          category: "Combos",
          inStock: true,
          extras: [],
        },
        quantity: 1,
        selectedExtras: [],
        observations: "Sin cebolla",
        totalPrice: 7200,
      },
    ],
    subtotal: 7200,
    shippingCost: 0,
    paymentAdjustment: -720,
    total: 6480,
    customer: {
      name: "Maria Garcia",
      phone: "3519876543",
      email: "maria@mail.com",
      shippingMethod: "retiro",
      street: "",
      number: "",
      neighborhood: "",
      paymentMethod: "transferencia",
      cashAmount: "",
      observations: "Sin cebolla por favor",
    },
    status: "CONFIRMADO",
    createdAt: "2026-02-21T14:28:00",
  },
  {
    id: "ORD-003",
    items: [
      {
        id: "ci-4",
        product: {
          id: "burger-3",
          name: "Picante Infernal",
          description: "",
          price: 5100,
          image: "/images/burger-picante.jpg",
          category: "Hamburguesas",
          inStock: true,
          extras: [],
        },
        quantity: 1,
        selectedExtras: [],
        observations: "",
        totalPrice: 5100,
      },
      {
        id: "ci-5",
        product: {
          id: "bebida-2",
          name: "Limonada Natural",
          description: "",
          price: 1800,
          image: "/images/bebida-limon.jpg",
          category: "Bebidas",
          inStock: true,
          extras: [],
        },
        quantity: 1,
        selectedExtras: [],
        observations: "",
        totalPrice: 1800,
      },
    ],
    subtotal: 6900,
    shippingCost: 800,
    paymentAdjustment: 690,
    total: 8390,
    customer: {
      name: "Carlos Rodriguez",
      phone: "3515551234",
      email: "",
      shippingMethod: "delivery",
      street: "Belgrano",
      number: "1200",
      neighborhood: "Nueva Cordoba",
      paymentMethod: "mercadopago",
      cashAmount: "",
      observations: "",
    },
    status: "EN_PREPARACION",
    createdAt: "2026-02-21T14:15:00",
  },
  {
    id: "ORD-004",
    items: [
      {
        id: "ci-6",
        product: {
          id: "combo-2",
          name: "Combo Doble",
          description: "",
          price: 10500,
          image: "/images/combo-clasico.jpg",
          category: "Combos",
          inStock: true,
          extras: [],
        },
        quantity: 2,
        selectedExtras: [{ id: "extra-1", name: "Medallon extra", price: 1200, inStock: true }],
        observations: "",
        totalPrice: 23400,
      },
    ],
    subtotal: 23400,
    shippingCost: 0,
    paymentAdjustment: 0,
    total: 23400,
    customer: {
      name: "Ana Lopez",
      phone: "3518887766",
      email: "ana@mail.com",
      shippingMethod: "retiro",
      street: "",
      number: "",
      neighborhood: "",
      paymentMethod: "efectivo",
      cashAmount: "25000",
      observations: "",
    },
    status: "LISTO",
    createdAt: "2026-02-21T13:50:00",
  },
  {
    id: "ORD-005",
    items: [
      {
        id: "ci-7",
        product: {
          id: "burger-2",
          name: "Doble Smash",
          description: "",
          price: 6200,
          image: "/images/burger-doble.jpg",
          category: "Hamburguesas",
          inStock: true,
          extras: [],
        },
        quantity: 1,
        selectedExtras: [
          { id: "extra-2", name: "Bacon", price: 800, inStock: true },
          { id: "extra-4", name: "Cheddar extra", price: 400, inStock: true },
        ],
        observations: "",
        totalPrice: 7400,
      },
    ],
    subtotal: 7400,
    shippingCost: 800,
    paymentAdjustment: 0,
    total: 8200,
    customer: {
      name: "Pedro Sanchez",
      phone: "3512223344",
      email: "pedro@mail.com",
      shippingMethod: "delivery",
      street: "Colon",
      number: "800",
      neighborhood: "Alberdi",
      paymentMethod: "efectivo",
      cashAmount: "10000",
      observations: "Tocar timbre 2B",
    },
    status: "ENTREGADO",
    createdAt: "2026-02-21T12:30:00",
  },
]
